markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : OpenCPU
description: "OpenCPU: producing and reproducing results."
disqus_shortname: opencpu
analytics: UA-701288-6
production_url: https://www.opencpu.org
url: https://www.opencpu.org
author :
  name : Jeroen Ooms
  github : opencpu
  twitter : opencpu
  email: jeroen.ooms@stat.ucla.edu
gems:
  - jekyll-redirect-from
